import mongoose from 'mongoose';

const flightSchema = new mongoose.Schema(
    {
        totalFlightPrice:String,
        departingFlights: {
            flightNumber1: String,
            airline1: String,
            airport1: String,
            departureTime1: String,
            duration1: String,
            arrivalTime1: String,
            layoverTime1: String,
            flightNumber2: String,
            airline2: String,
            airport2: String,
            departureTime2: String,
            duration2: String,
            arrivalTime2: String,
            layoverTime2: String,
            flightNumber3: String,
            airline3: String,
            airport3: String,
            departureTime3: String,
            duration3: String,
            arrivalTime3: String,
            destinationAirport: String,
          },
          returningFlights: {
            flightNumber1: String,
            airline1: String,
            airport1: String,
            departureTime1: String,
            duration1: String,
            arrivalTime1: String,
            layoverTime1: String,
            flightNumber2: String,
            airline2: String,
            airport2: String,
            departureTime2: String,
            duration2: String,
            arrivalTime2: String,
            layoverTime2: String,
            flightNumber3: String,
            airline3: String,
            airport3: String,
            departureTime3: String,
            duration3: String,
            arrivalTime3: String,
            originAirport: String,
          },
    }
    );

export const Flight = mongoose.model('flight', flightSchema);