import mongoose from 'mongoose';

const flightSchema = new mongoose.Schema(
    {
        departingFlights: {
            flightNumber1: String,
            airline1: String,
            airport1: String,
            departureTime1: Date,
            duration1: String,
            arrivalTime1: Date,
            layoverTime1: String,
            flightNumber2: String,
            airline2: String,
            airport2: String,
            departureTime2: Date,
            duration2: String,
            arrivalTime2: Date,
            layoverTime2: String,
            flightNumber3: String,
            airline3: String,
            airport3: String,
            departureTime3: Date,
            duration3: String,
            arrivalTime3: Date,
            destinationAirport: String,
          },
          returningFlights: {
            flightNumber1: String,
            airline1: String,
            airport1: String,
            departureTime1: Date,
            duration1: String,
            arrivalTime1: Date,
            layoverTime1: String,
            flightNumber2: String,
            airline2: String,
            airport2: String,
            departureTime2: Date,
            duration2: String,
            arrivalTime2: Date,
            layoverTime2: String,
            flightNumber3: String,
            airline3: String,
            airport3: String,
            departureTime3: Date,
            duration3: String,
            arrivalTime3: Date,
            originAirport: String,
          },
          totalPrice: Number,
    }
    );

export const Flight = mongoose.model('flight', flightSchema);